In [1]:
import numpy as np
import pandas as pd

In [2]:
R_dark_f=np.linspace(141,139,500)

In [3]:
R_dark_f

array([141.        , 140.99599198, 140.99198397, 140.98797595,
       140.98396794, 140.97995992, 140.9759519 , 140.97194389,
       140.96793587, 140.96392786, 140.95991984, 140.95591182,
       140.95190381, 140.94789579, 140.94388778, 140.93987976,
       140.93587174, 140.93186373, 140.92785571, 140.9238477 ,
       140.91983968, 140.91583166, 140.91182365, 140.90781563,
       140.90380762, 140.8997996 , 140.89579158, 140.89178357,
       140.88777555, 140.88376754, 140.87975952, 140.8757515 ,
       140.87174349, 140.86773547, 140.86372745, 140.85971944,
       140.85571142, 140.85170341, 140.84769539, 140.84368737,
       140.83967936, 140.83567134, 140.83166333, 140.82765531,
       140.82364729, 140.81963928, 140.81563126, 140.81162325,
       140.80761523, 140.80360721, 140.7995992 , 140.79559118,
       140.79158317, 140.78757515, 140.78356713, 140.77955912,
       140.7755511 , 140.77154309, 140.76753507, 140.76352705,
       140.75951904, 140.75551102, 140.75150301, 140.74

In [4]:
R_dark=R_dark_f.astype(int)

In [5]:
R_dark

array([141, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140,
       140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140,
       140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140,
       140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140,
       140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140,
       140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140,
       140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140,
       140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140,
       140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140,
       140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140,
       140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140,
       140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140,
       140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140,
       140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 14

In [6]:
G_dark_f=np.linspace(85,112,500)

In [7]:
G_dark=G_dark_f.astype(int)

In [8]:
G_dark


array([ 85,  85,  85,  85,  85,  85,  85,  85,  85,  85,  85,  85,  85,
        85,  85,  85,  85,  85,  85,  86,  86,  86,  86,  86,  86,  86,
        86,  86,  86,  86,  86,  86,  86,  86,  86,  86,  86,  87,  87,
        87,  87,  87,  87,  87,  87,  87,  87,  87,  87,  87,  87,  87,
        87,  87,  87,  87,  88,  88,  88,  88,  88,  88,  88,  88,  88,
        88,  88,  88,  88,  88,  88,  88,  88,  88,  89,  89,  89,  89,
        89,  89,  89,  89,  89,  89,  89,  89,  89,  89,  89,  89,  89,
        89,  89,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,
        90,  90,  90,  90,  90,  90,  90,  91,  91,  91,  91,  91,  91,
        91,  91,  91,  91,  91,  91,  91,  91,  91,  91,  91,  91,  91,
        92,  92,  92,  92,  92,  92,  92,  92,  92,  92,  92,  92,  92,
        92,  92,  92,  92,  92,  93,  93,  93,  93,  93,  93,  93,  93,
        93,  93,  93,  93,  93,  93,  93,  93,  93,  93,  93,  94,  94,
        94,  94,  94,  94,  94,  94,  94,  94,  94,  94,  94,  9

In [9]:
B_dark_f=np.linspace(36,84,500)
B_dark=B_dark_f.astype(int)
B_dark

array([36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 37, 37, 37, 37, 37,
       37, 37, 37, 37, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 39, 39,
       39, 39, 39, 39, 39, 39, 39, 39, 40, 40, 40, 40, 40, 40, 40, 40, 40,
       40, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 42, 42, 42, 42, 42,
       42, 42, 42, 42, 42, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 44,
       44, 44, 44, 44, 44, 44, 44, 44, 44, 45, 45, 45, 45, 45, 45, 45, 45,
       45, 45, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 47, 47, 47, 47,
       47, 47, 47, 47, 47, 47, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
       49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 52, 52, 52,
       52, 52, 52, 52, 52, 52, 52, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53,
       53, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 57, 57,
       57, 57, 57, 57, 57

In [10]:
dark_f=np.linspace(1,1,500)
dark=dark_f.astype(int)
dark

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [11]:
R_mild_f=np.linspace(139,180,500)
R_mild=R_mild_f.astype(int)
R_mild

array([139, 139, 139, 139, 139, 139, 139, 139, 139, 139, 139, 139, 139,
       140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 140, 141,
       141, 141, 141, 141, 141, 141, 141, 141, 141, 141, 141, 142, 142,
       142, 142, 142, 142, 142, 142, 142, 142, 142, 142, 143, 143, 143,
       143, 143, 143, 143, 143, 143, 143, 143, 143, 144, 144, 144, 144,
       144, 144, 144, 144, 144, 144, 144, 144, 144, 145, 145, 145, 145,
       145, 145, 145, 145, 145, 145, 145, 145, 146, 146, 146, 146, 146,
       146, 146, 146, 146, 146, 146, 146, 147, 147, 147, 147, 147, 147,
       147, 147, 147, 147, 147, 147, 148, 148, 148, 148, 148, 148, 148,
       148, 148, 148, 148, 148, 149, 149, 149, 149, 149, 149, 149, 149,
       149, 149, 149, 149, 150, 150, 150, 150, 150, 150, 150, 150, 150,
       150, 150, 150, 150, 151, 151, 151, 151, 151, 151, 151, 151, 151,
       151, 151, 151, 152, 152, 152, 152, 152, 152, 152, 152, 152, 152,
       152, 152, 153, 153, 153, 153, 153, 153, 153, 153, 153, 15

In [12]:
G_mild_f=np.linspace(114,143,500)
G_mild=G_mild_f.astype(int)
G_mild

array([114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114,
       114, 114, 114, 114, 114, 115, 115, 115, 115, 115, 115, 115, 115,
       115, 115, 115, 115, 115, 115, 115, 115, 115, 116, 116, 116, 116,
       116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116, 116,
       117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117,
       117, 117, 117, 117, 118, 118, 118, 118, 118, 118, 118, 118, 118,
       118, 118, 118, 118, 118, 118, 118, 118, 118, 119, 119, 119, 119,
       119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119,
       120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120,
       120, 120, 120, 120, 121, 121, 121, 121, 121, 121, 121, 121, 121,
       121, 121, 121, 121, 121, 121, 121, 121, 122, 122, 122, 122, 122,
       122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 122, 123,
       123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123,
       123, 123, 123, 123, 124, 124, 124, 124, 124, 124, 124, 12

In [13]:
B_mild_f=np.linspace(84,123,500)
B_mild=B_mild_f.astype(int)
B_mild

array([ 84,  84,  84,  84,  84,  84,  84,  84,  84,  84,  84,  84,  84,
        85,  85,  85,  85,  85,  85,  85,  85,  85,  85,  85,  85,  85,
        86,  86,  86,  86,  86,  86,  86,  86,  86,  86,  86,  86,  86,
        87,  87,  87,  87,  87,  87,  87,  87,  87,  87,  87,  87,  87,
        88,  88,  88,  88,  88,  88,  88,  88,  88,  88,  88,  88,  89,
        89,  89,  89,  89,  89,  89,  89,  89,  89,  89,  89,  89,  90,
        90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  91,
        91,  91,  91,  91,  91,  91,  91,  91,  91,  91,  91,  91,  92,
        92,  92,  92,  92,  92,  92,  92,  92,  92,  92,  92,  92,  93,
        93,  93,  93,  93,  93,  93,  93,  93,  93,  93,  93,  94,  94,
        94,  94,  94,  94,  94,  94,  94,  94,  94,  94,  94,  95,  95,
        95,  95,  95,  95,  95,  95,  95,  95,  95,  95,  95,  96,  96,
        96,  96,  96,  96,  96,  96,  96,  96,  96,  96,  96,  97,  97,
        97,  97,  97,  97,  97,  97,  97,  97,  97,  97,  97,  9

In [14]:
R_fair_f=np.linspace(224,176,500)
R_fair=R_fair_f.astype(int)
R_fair

array([224, 223, 223, 223, 223, 223, 223, 223, 223, 223, 223, 222, 222,
       222, 222, 222, 222, 222, 222, 222, 222, 221, 221, 221, 221, 221,
       221, 221, 221, 221, 221, 221, 220, 220, 220, 220, 220, 220, 220,
       220, 220, 220, 219, 219, 219, 219, 219, 219, 219, 219, 219, 219,
       218, 218, 218, 218, 218, 218, 218, 218, 218, 218, 218, 217, 217,
       217, 217, 217, 217, 217, 217, 217, 217, 216, 216, 216, 216, 216,
       216, 216, 216, 216, 216, 216, 215, 215, 215, 215, 215, 215, 215,
       215, 215, 215, 214, 214, 214, 214, 214, 214, 214, 214, 214, 214,
       213, 213, 213, 213, 213, 213, 213, 213, 213, 213, 213, 212, 212,
       212, 212, 212, 212, 212, 212, 212, 212, 211, 211, 211, 211, 211,
       211, 211, 211, 211, 211, 211, 210, 210, 210, 210, 210, 210, 210,
       210, 210, 210, 209, 209, 209, 209, 209, 209, 209, 209, 209, 209,
       208, 208, 208, 208, 208, 208, 208, 208, 208, 208, 208, 207, 207,
       207, 207, 207, 207, 207, 207, 207, 207, 206, 206, 206, 20

In [15]:
G_fair_f=np.linspace(172,141,500)
G_fair=G_fair_f.astype(int)
G_fair

array([172, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171, 171,
       171, 171, 171, 171, 170, 170, 170, 170, 170, 170, 170, 170, 170,
       170, 170, 170, 170, 170, 170, 170, 169, 169, 169, 169, 169, 169,
       169, 169, 169, 169, 169, 169, 169, 169, 169, 169, 168, 168, 168,
       168, 168, 168, 168, 168, 168, 168, 168, 168, 168, 168, 168, 168,
       167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167,
       167, 167, 167, 166, 166, 166, 166, 166, 166, 166, 166, 166, 166,
       166, 166, 166, 166, 166, 166, 165, 165, 165, 165, 165, 165, 165,
       165, 165, 165, 165, 165, 165, 165, 165, 165, 164, 164, 164, 164,
       164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 164, 163,
       163, 163, 163, 163, 163, 163, 163, 163, 163, 163, 163, 163, 163,
       163, 163, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162, 162,
       162, 162, 162, 162, 162, 161, 161, 161, 161, 161, 161, 161, 161,
       161, 161, 161, 161, 161, 161, 161, 161, 161, 160, 160, 16

In [16]:
B_fair_f=np.linspace(105,132,500)
B_fair=B_fair_f.astype(int)
B_fair

array([105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105, 105,
       105, 105, 105, 105, 105, 105, 106, 106, 106, 106, 106, 106, 106,
       106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 106, 107, 107,
       107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107, 107,
       107, 107, 107, 107, 108, 108, 108, 108, 108, 108, 108, 108, 108,
       108, 108, 108, 108, 108, 108, 108, 108, 108, 109, 109, 109, 109,
       109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109, 109,
       109, 109, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110,
       110, 110, 110, 110, 110, 110, 110, 111, 111, 111, 111, 111, 111,
       111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111,
       112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112,
       112, 112, 112, 112, 112, 113, 113, 113, 113, 113, 113, 113, 113,
       113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 114, 114,
       114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 11

In [17]:
mild_f=np.linspace(2,2,500)
mild=mild_f.astype(int)
mild

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [18]:
fair_f=np.linspace(3,3,500)
fair=fair_f.astype(int)
fair

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,

In [19]:
R = np.append(R_dark, R_mild)

In [20]:
R = np.append(R, R_fair)

In [21]:
G=np.append(G_dark, G_mild)

In [22]:
G = np.append(G, G_fair)

In [23]:
B=np.append(B_dark, B_mild)
B = np.append(B, B_fair)

In [24]:
skintone=np.append(dark,mild)

In [25]:
skintone=np.append(skintone,fair)

In [26]:
data=pd.DataFrame(R,columns=['R'])

In [27]:
data

R
0     141
1     140
2     140
3     140
4     140
...   ...
1495  176
1496  176
1497  176
1498  176
1499  176

[1500 rows x 1 columns]

In [28]:
data['G']=G

In [29]:
data

R    G
0     141   85
1     140   85
2     140   85
3     140   85
4     140   85
...   ...  ...
1495  176  141
1496  176  141
1497  176  141
1498  176  141
1499  176  141

[1500 rows x 2 columns]

In [30]:
data['B']=B
data['skintone']=skintone

In [31]:
data

R    G    B  skintone
0     141   85   36         1
1     140   85   36         1
2     140   85   36         1
3     140   85   36         1
4     140   85   36         1
...   ...  ...  ...       ...
1495  176  141  131         3
1496  176  141  131         3
1497  176  141  131         3
1498  176  141  131         3
1499  176  141  132         3

[1500 rows x 4 columns]

In [32]:
x= data.iloc[:, [0,1,2]].values  
y= data.iloc[:, 3].values    
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.20, random_state=0) 
  
 

In [33]:
x

array([[141,  85,  36],
       [140,  85,  36],
       [140,  85,  36],
       ...,
       [176, 141, 131],
       [176, 141, 131],
       [176, 141, 132]])

In [34]:
y

array([1, 1, 1, ..., 3, 3, 3])

In [35]:
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
classifier.fit(x_train, y_train)  

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [36]:
y_pred= classifier.predict(x_test)  

In [38]:
from sklearn.metrics import accuracy_score 
accuracy_score(y_test, y_pred) 

1.0

In [ ]:
import cv2
from sklearn.cluster import KMeans
from collections import Counter
import imutils
from matplotlib import pyplot as plt

In [ ]:
rgb_lower = [141,85,36]
rgb_higher = [255,219,172]
skin_shades = {
    'dark' : [rgb_lower,[198,134,66]],
    'mild' : [[198,134,66],[224,172,105]],
    'fair':[[224,172,105],[241,194,125]],
    'bright' : [[241,194,125],rgb_higher]
}
convert_skintones = {}
for shade in skin_shades:
    convert_skintones.update({
        shade : [
            (skin_shades[shade][0][0] * 256 * 256) + (skin_shades[shade][0][1] * 256) + skin_shades[shade][0][2],
            (skin_shades[shade][1][0] * 256 * 256) + (skin_shades[shade][1][1] * 256) + skin_shades[shade][1][2]
        ]
    })

def extractSkin(image):
    img = image.copy()
    black_img = np.zeros((img.shape[0],img.shape[1],img.shape[2]),dtype=np.uint8)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    lower_threshold = np.array([0, 48, 80], dtype=np.uint8)
    print(lower_threshold)
    upper_threshold = np.array([20, 255, 255], dtype=np.uint8)
    print(upper_threshold)

    skinMask = cv2.inRange(img, lower_threshold, upper_threshold)
    skin = cv2.bitwise_and(img, img, mask=skinMask)
    return cv2.cvtColor(skin, cv2.COLOR_HSV2BGR)

def removeBlack(estimator_labels, estimator_cluster):
    hasBlack = False
    occurance_counter = Counter(estimator_labels)
    def compare(x, y): return Counter(x) == Counter(y)
    for x in occurance_counter.most_common(len(estimator_cluster)):
        color = [int(i) for i in estimator_cluster[x[0]].tolist()]
        if compare(color, [0, 0, 0]) == True:
            del occurance_counter[x[0]]
            hasBlack = True
            estimator_cluster = np.delete(estimator_cluster, x[0], 0)
            break
    return (occurance_counter, estimator_cluster, hasBlack)

def getColorInformation(estimator_labels, estimator_cluster, hasThresholding=False):
    occurance_counter = None
    colorInformation = []
    hasBlack = False
    if hasThresholding == True:
        (occurance, cluster, black) = removeBlack(
            estimator_labels, estimator_cluster)
        occurance_counter = occurance
        estimator_cluster = cluster
        hasBlack = black
    else:
        occurance_counter = Counter(estimator_labels)
    totalOccurance = sum(occurance_counter.values())
    for x in occurance_counter.most_common(len(estimator_cluster)):
        index = (int(x[0]))
        index = (index-1) if ((hasThresholding & hasBlack)
                              & (int(index) != 0)) else index
        color = estimator_cluster[index].tolist()
        color_percentage = (x[1]/totalOccurance)
        colorInfo = {"cluster_index": index, "color": color,
                     "color_percentage": color_percentage}
        colorInformation.append(colorInfo)
    return colorInformation

def extractDominantColor(image, number_of_colors=1, hasThresholding=False):
    if hasThresholding == True:
        number_of_colors += 1
    img = image.copy()
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img.reshape((img.shape[0]*img.shape[1]), 3)
    estimator = KMeans(n_clusters=number_of_colors, random_state=0)
    estimator.fit(img)
    colorInformation = getColorInformation(
        estimator.labels_, estimator.cluster_centers_, hasThresholding)
    return colorInformation

def plotColorBar(colorInformation):
    color_bar = np.zeros((100, 500, 3), dtype="uint8")
    top_x = 0
    for x in colorInformation:
        bottom_x = top_x + (x["color_percentage"] * color_bar.shape[1])
        color = tuple(map(int, (x['color'])))
        cv2.rectangle(color_bar, (int(top_x), 0),
                      (int(bottom_x), color_bar.shape[0]), color, -1)
        top_x = bottom_x
    return color_bar

url = input("Enter image url :")

image = imutils.url_to_image(url)

image = imutils.resize(image, width=250)
plt.subplot(3, 1, 1)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.title("Original Image")

skin = extractSkin(image)
plt.subplot(3, 1, 2)
plt.imshow(cv2.cvtColor(skin, cv2.COLOR_BGR2RGB))
plt.title("Thresholded  Image")

unprocessed_dominant = extractDominantColor(skin, number_of_colors=1, hasThresholding=True)

decimal_lower = (rgb_lower[0] * 256 * 256) + (rgb_lower[1] * 256) + rgb_lower[2]
decimal_higher = (rgb_higher[0] * 256 * 256) + (rgb_higher[1] * 256) + rgb_higher[2]
dominantColors = []
for clr in unprocessed_dominant:
    clr_decimal = int((clr['color'][0] * 256 * 256) + (clr['color'][1] * 256) + clr['color'][2])
    if clr_decimal in range(decimal_lower,decimal_higher+1):
        clr['decimal_color'] = clr_decimal
        dominantColors.append(clr)

skin_tones = []
if len(dominantColors) == 0:
    skin_tones.append('Unrecognized')
else:
    for color in dominantColors:
        for shade in convert_skintones:
            if color['decimal_color'] in range(convert_skintones[shade][0],convert_skintones[shade][1]+1):
                skin_tones.append(shade)

print(skin_tones)

print("Color Bar")
colour_bar = plotColorBar(dominantColors)
plt.subplot(3, 1, 3)
plt.axis("off")
plt.imshow(colour_bar)
plt.title("Color Bar")

plt.tight_layout()
plt.show()

rgbv=colour_bar[0][0]
rgbl=list(rgbv)
print(rgbl)


In [ ]:
shade=classifier.predict([rgbl])  
print("The predicted skintone is:")
if shade==[1]:
    print("DARK")
elif shade==[2]:
    print("MILD")
elif shade==[3]:
    print("FAIR")